Use dataanalyst;
Select top 10 * from  dbo.Shopping_Data;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT 
    Gender, 
    SUM([Purchase Amount (USD)]) AS Total_Revenue
FROM dbo.Shopping_Data
GROUP BY Gender;
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    [Customer ID], 
    [Purchase Amount (USD)]
FROM dbo.Shopping_Data
WHERE [Discount Applied] = 'Yes' 
  AND [Purchase Amount (USD)] > (SELECT AVG([Purchase Amount (USD)]) FROM dbo.Shopping_Data);
-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    [Item Purchased], 
    AVG([Review Rating]) AS Avg_Rating
FROM dbo.Shopping_Data
GROUP BY [Item Purchased]
ORDER BY Avg_Rating DESC;
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    [Shipping Type], 
    AVG([Purchase Amount (USD)]) AS Avg_Purchase
FROM dbo.Shopping_Data
WHERE [Shipping Type] IN ('Standard', 'Express')
GROUP BY [Shipping Type];
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
    [Subscription Status], 
    AVG([Purchase Amount (USD)]) AS Avg_Spend, 
    SUM([Purchase Amount (USD)]) AS Total_Revenue
FROM dbo.Shopping_Data
GROUP BY [Subscription Status];
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 
    [Item Purchased], 
    COUNT(CASE WHEN [Discount Applied] = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS Discount_Percentage
FROM dbo.Shopping_Data
GROUP BY [Item Purchased]
ORDER BY Discount_Percentage DESC;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases.
SELECT 
    [Customer ID], 
    [Previous Purchases],
    CASE 
        WHEN [Previous Purchases] < 5 THEN 'New'
        WHEN [Previous Purchases] BETWEEN 5 AND 15 THEN 'Returning'
        ELSE 'Loyal'
    END AS Customer_Segment
FROM dbo.Shopping_Data;

-- Q8. What are the top 3 most purchased products within each category?
SELECT * FROM (
    SELECT 
        Category, 
        [Item Purchased], 
        COUNT(*) AS Purchase_Count,
        ROW_NUMBER() OVER(PARTITION BY Category ORDER BY COUNT(*) DESC) AS Rank
    FROM dbo.Shopping_Data
    GROUP BY Category, [Item Purchased]
) AS RankedProducts
WHERE Rank <= 3;
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    [Subscription Status], 
    COUNT(*) AS Customer_Count
FROM dbo.Shopping_Data
WHERE [Previous Purchases] > 5
GROUP BY [Subscription Status];

-- Q10. What is the revenue contribution of each age group?

SELECT 
    CASE 
        WHEN Age < 20 THEN 'Under 20'
        WHEN Age BETWEEN 20 AND 35 THEN '20-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE 'Over 50'
    END AS Age_Group,
    SUM([Purchase Amount (USD)]) AS Total_Revenue
FROM dbo.Shopping_Data
GROUP BY 
    CASE 
        WHEN Age < 20 THEN 'Under 20'
        WHEN Age BETWEEN 20 AND 35 THEN '20-35'
        WHEN Age BETWEEN 36 AND 50 THEN '36-50'
        ELSE 'Over 50'
    END;